// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyBc6ryd-oY5FUoiI3lqRyNQf_vSMxK2zfE",
  authDomain: "babearia-palatinus.firebaseapp.com",
  projectId: "babearia-palatinus",
  storageBucket: "babearia-palatinus.firebasestorage.app",
  messagingSenderId: "187763891668",
  appId: "1:187763891668:web:8de5c72e3d8f6a787c4a41"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);